version: '3'
services:
  configuration:
    build:
      context: ./non-functional/configuration-service/
      dockerfile: Dockerfile
    image: configuration-service
    ports:
      - 9090:9090

  gateway:
      build:
        context: ./non-functional/gateway-service/
        dockerfile: Dockerfile
      image: gateway-service
      ports:
        - 8081:8081

  registry:
        build:
          context: ./non-functional/registry-service/
          dockerfile: Dockerfile
        image: registry-service
        ports:
          - 9091:9091

