token:
  signingKey: MIICszCCAZsCAQAwbjELMAkGA1UEBhMCSU4xDjAMBgNVBAMMBWRlbmR5MQ8wDQYDVQQHDAZCYW50dWwxEDAOBgNVBAoMB21pdHJhaXMxHjAcBgNVBAgMFVlvZ3lha2FydGEvRElZL0JhbnR1bDEMMAoGA1UECwwDZGV2MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwOajjDy1yVSwgfjZtJUa4gCONRLFk7soSTyEqZQqi9GztysSoux5kOLg39MOm0iu/kUzBaqfFtS2Th+O1EvX/4y844aJThrWNOYOPEzvHOM8Y7UwiNNWekGcmCDQNjW85gAumX0rSJLxA7g5D46NvctoYlnDICbsJWmJQF2VDPcYRRZ/TV2kKnWJh/EXvr64lcELOWYfUKIDVSio1nusEamfGeC26EM9zNMSqOk4MiF3FzzFOtgCHM2hl9ZpYzdoH8w7XB68i39FscIgZL4puBwsVARaOZ15ucuV3ZUUZUju6E8pYATvaGEiOtIwP+wQSKZJag7IQHebsDLH0rqQLQIDAQABoAAwDQYJKoZIhvcNAQELBQADggEBAKJBZvtSbxOdaMrPtnS/M2eGgv8LPmpSQ+j7olxJirBY1Xs37bYvBE39JhDTCl7JgW8te9IDQkaQYgRtkKEWKOeaHf06shhIcsqdv3RqPSN3zE8006NgvsGVA0nqu6m79Bk8rcT7B6e+u36dwZMyObxCX/QrYDWIwlNsXGOuuvJ7SGS84afWF/pyCA2Bo9vm14v1EjiNEFINh3VzvftYOhMy0dp+zvLBNzS2/UMIXUH20bFozirTgM3ND5qNcMxBDyA6sVEgbZzR1+EKHA5zgIoGsFF1t/BkMazVwb8uCEBqpF1R0MtMoAShux4sVladfqH9jzh2hfjQu3JbYsymy70=

jdbc:
  driverClassName: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/1stopclick_movie
  user: root
  pass:

hibernate:
  dialect: org.hibernate.dialect.MySQL5Dialect
  show_sql: true
  hbm2ddl:
    auto: validate

logging:
  level:
    org.springframework.data.rest: DEBUG

# EUREKA DISCOVERY
eureka:
  client:
    healthcheck:
      enabled: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:9091/eureka
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION
# TOMCAT
server:
  port: 8091
# ACTUATOR ENDPOINTS
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - env

---
spring:
  profiles: docker
# EUREKA DISCOVERY
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://node0.registry/eureka, http://node1.registry/eureka # HA in docker environment
  instance:
    instanceId: ${spring.application.name}:${HOSTNAME}
# TOMCAT
server:
  port: 80
